#!/bin/bash

CXX_STANDARD=17

DEBUG_BUILD=1
UNITY_BUILD=1
DLL_BUILD=0
INCLUDE_TEXTURES=0
UI_EDITOR=0
MALLOCATOR=1

BUILD_SETTING="-DASUKA_DEBUG=$DEBUG_BUILD -DUNITY_BUILD=$UNITY_BUILD -DASUKA_DLL_BUILD=$DLL_BUILD -DIN_CODE_TEXTURES=$INCLUDE_TEXTURES -DUI_EDITOR=$UI_EDITOR -DASUKA_MALLOCATOR=$MALLOCATOR -std=c++$CXX_STANDARD"

g++ src/linux_main.cpp -o build/main -g3 $BUILD_SETTING -DASUKA_OS_LINUX -Icommon -Isrc -lX11 -lasound
